# Generated by Django 4.1 on 2022-10-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'users')], default=2),
        ),
    ]
